// src/components/ui/icons.tsx
'use client'

import { 
  LayoutDashboard,
  Users,
  Settings,
  ShoppingBag,
  FileText,
  BarChart3,
  LogOut,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  Home,
  UserCog,
  Bell,
  Search,
  Plus,
  Edit,
  Trash2,
  Eye,
  Check,
  AlertCircle,
  Loader2,
  User,
  Mail,
  Shield,
  Crown,
  UserCheck,
} from 'lucide-react'

export const Icons = {
  dashboard: LayoutDashboard,
  users: Users,
  settings: Settings,
  shopping: ShoppingBag,
  file: FileText,
  chart: BarChart3,
  logout: LogOut,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  home: Home,
  userCog: UserCog,
  bell: Bell,
  search: Search,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  eye: Eye,
  check: Check,
  alert: AlertCircle,
  loader: Loader2,
  user: User,
  mail: Mail,
  shield: Shield,
  crown: Crown,
  userCheck: UserCheck,
}